- UpcyProject/urls.py
- users/services.py
- users/urls.py
- users/views.py
전화번호 인증과 재학증명서 등록을 제외한 리포머 회원가입 api입니다.
> feat: Sign Up for Reformer eccept certification

- users/services.py
- users/urls.py
- users/views.py
소비자 회원가입 API
입력필드:
[이메일,
비밀번호,
전화번호,
프로필사진,
약관동의여부,
지역,
선호스타일,]
> Make Consumer Signup APIonsumer

- users/selectors.py
- users/services.py
- users/urls.py
- users/views.py
> feat: UserLogin

- UpcyProject/settings.py
> fix: Make Login Session

- products/services.py
- users/services.py
- users/views.py
리포머 회원가입 필드 변경(IA 맞춤)
- school, career, lisence에 대한 ability와 certification 추가
- bio삭제 후 links 입력 받음
- thumbnail_image입력 추가
> feat: Modify Reformer SIgnUp to Match IA

- UpcyProject/settings.py
> chore : add ALLOWED HOSTS

- users/services.py
- users/urls.py
- users/views.py
리포머 회원가입과 소비자 회원가입 병합 및 간소화
- 이전 회원가입들 일단 주석처리 해둠, 후에 참고 후 리팩토링
> #9 fix : merge reformer signup&consumer signup

- products/services.py
- users/services.py
- users/urls.py
- users/views.py
프로필 등록 api 작성
- 학교/경력 인증 부분 추가 필요 (디자인팀과 논의 필요)
> #9 feat : create profile register api

- users/admin.py
- users/services.py
- users/urls.py
- users/views.py
- competition 이름
- 주최 기관
- 수상 날짜
- 증명 파일
> #9 feat: create competition profile api

- users/admin.py
- users/services.py
- users/urls.py
- users/views.py
> #9 feat: create internship_register api

- users/admin.py
- users/services.py
- users/urls.py
- users/views.py
> #9 feat: create freelancer_register api

- users/views.py
- 유저 회원가입
- 유저 로그인
- 리포머 프로필 등록
- 리포머 경력 등록 -> 자격증, 공모전, 인턴, 프리랜서/외주
> #39 feat : make swagger for user's api

- UpcyProject/settings.py
- UpcyProject/urls.py
commit 넣고 pr 올리기 전에 branch 왔다갔다 하다가 이전에 기본 세팅해뒀던 코드들 사라져서 재작성 후 pr 날립니다!
> #39 fix : add swagger default setting again

- products/views.py
> #39 feat : write swagger of products

- services/views.py
> #39 feat: make swagger of services api

- .dockerignore
- Dockerfile
- UpcyProject/urls.py
- docker-compose.yml
- requirements.txt
- requirement.txt > python-dotenv version 변경 ( 1.0.0 )
- requirement.txt >  redjango-sslserver 추가
- swagger url 작성 방식 변경 ( path -> re_path )
- Docker 연결
* https -> 현재 redjango-sslserver 사용중.
* 추후  리버스 프록시 서버(Nginx, Traefik)로 변경할 가능성 있음
> #61 feat : link Docker

- .config/nginx/UPCY.conf
- .config/uwsgi/UPCY.ini
- .config/uwsgi/uwsgi.service
nginx conf 파일 작성
그에 따른 uwsgi,.ini 파일 수정 및 uwsgi.service 파일 작성하여 백그라운드에 돌도록
> #59 feat : set nginx conf file

- .config/uwsgi/UPCY.ini
module 경로 UPCY.settings -> UpcyProject.settings로 수정
> #59 fix : modify module route

- .config/uwsgi/uwsgi.service
- UpcyProject/settings/production.py
- UpcyProject/settings/settings.py
settings.py 하나로 굴러가던 module 파일
- settings > settings.py(로컬용) , production.py (서버용)으로 분리
> #59 fix : modify settings directory&move settings.py here

- .config/uwsgi/uwsgi.service
environment 루트에 오류가 있어서
settings.production으로 수정
> #59 fix : modify server environment route

- .config/nginx/UPCY.conf
- certbot 이용한 ssl 인증서 추가
- http 로 접속시 https 로 redirect
- certbot 인증서 자동 갱신
> #59 feat : add ssl certificates & update nginx conf setting

- users/serializers/user_signup_serializer.py
- users/services.py
> ㄴㅁㅇㄻㄴㅇㄻㄴㅇㄹ

- Dockerfile
- users/models/user.py
- users/serializers/user_signup_serializer.py
- agreement_terms = 선택 약관이므로 Serializer validator에서 TRUE만 받아야 한다는 소스코드 제거
- nickname = 요구사항에 의해 required = False로 설정
> Fix : User signup api 수정

- market/models.py
- Market models.py lazy loading으로 인한 migrate 수행 시 발생하는 문제 해결
> migrate error fix

- order/models.py
1.리폼할 의류 이미지/추가 요청사항 이미지 구분
2.거래방식 관리 class 따로 작성
3.택배방식 관리 class 따로 작성
카테고리나 이런 건 외부키로 가져오는 게 나을 것 같아서 추후에 수정할 예정~!
> 110 feat : modify order models.py

- market/admin.py
- market/models.py
- market/serializers/service_serializers/service_style/service_style_create_serializer.py
- market/serializers/service_serializers/service_style/service_style_retrieve_serializer.py
- market/serializers/service_serializers/service_style/service_style_update_serializer.py
- market/urls.py
- market/views/service_view/service_style/service_style_view.py
> Add new feature to market service

- market/pagination.py
- market/urls.py
- market/views/service_view/service_create_list_view.py
- 전체 서비스 정보를 반환하는 API 추가
- 기초적인 페이지네이션 기능 적용 (추후 여러가지 데이터를 전달하는 모든 GET API에 대해 페이지네이션을 적용할 예정입니다.)
> 모든 서비스 정보를 반환하는 API 생성 + 기초적인 페이지네이션 기능 적용

- users/tests.py
- users/views/user_view/user_crud_view.py
> user delete api 수정

- users/serializers/reformer_serializer/reformer_profile_serializer.py
- users/urls.py
- users/views/reformer_view/reformer_career_view/reformer_career_create_list_view.py
- users/views/reformer_view/reformer_career_view/reformer_career_document_view.py
- users/views/reformer_view/reformer_career_view/reformer_career_view.py
- users/views/reformer_view/reformer_freelancer_view/reformer_freelancer_create_list_view.py
- users/views/reformer_view/reformer_freelancer_view/reformer_freelancer_document_view.py
- users/views/reformer_view/reformer_freelancer_view/reformer_freelancer_view.py
- reformer career api 추가
- reformer freelancer api 추가
- reformer serializer 수정
- reformer 관련 url 수정
- black, isort 적용
> 리포머 경력, 프리랜서 경력 관련 API 추가
